package com.myspace.book_recommender;

import com.myspace.book_recommender.User
import com.myspace.book_recommender.BookRecommendation


rule "Lang-ita"
    when
        user: User(nationality == "ITA")
        bookrec: BookRecommendation(language == null)
    then
        bookrec.setLanguage("ITA");
end

rule "Lang-deu"
    when
        user: User(nationality == "DEU" || == "AUT")
        bookrec: BookRecommendation(language == null)
    then
        bookrec.setLanguage("DEU");
end
