package com.myspace.book_recommender;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BookRecommendation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String language;
	private java.lang.String author;
	private java.util.List<java.lang.String> subject;

	public BookRecommendation() {
	}

	public java.lang.String getAuthor() {
		return this.author;
	}

	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	public java.util.List<java.lang.String> getSubject() {
		return this.subject;
	}

	public void setSubject(java.util.List<java.lang.String> subject) {
		this.subject = subject;
	}

	public java.lang.String getLanguage() {
		return this.language;
	}

	public void setLanguage(java.lang.String language) {
		this.language = language;
	}

	public BookRecommendation(java.lang.String language,
			java.lang.String author, java.util.List<java.lang.String> subject) {
		this.language = language;
		this.author = author;
		this.subject = subject;
	}

}
